name: m_k_w
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  cloud_firestore: ^0.12.9
  flutter_swiper : any
  firebase_auth : 0.11.1
  flutter_facebook_login : ^2.0.1
  shared_preferences : any
  google_sign_in: ^4.0.4
  google_maps_flutter: ^0.5.11
  permission_handler: ^3.2.0
  http: ^0.12.0+1
  json_serializable: ^2.0.2
  url_launcher: ^5.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic: ^1.4.0
  build_runner: ^1.2.7
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/album00.jpg
    - assets/album01.jpg
    - assets/album02.jpg
    - assets/album03.jpg
    - assets/album04.jpg
    - assets/album05.jpg
    - assets/album06.jpg
    - assets/album07.jpg
    - assets/album08.jpg
    - assets/album09.jpg
    - assets/album10.jpg
    - assets/album11.jpg
    - assets/album12.jpg
    - assets/album13.jpg
    - assets/album14.jpg
    - assets/album15.jpg
    - assets/album16.jpg
    - assets/album17.jpg
    - assets/album18.jpg
    - assets/album19.jpg
    - assets/album20.jpg
    - assets/album21.jpg
    - assets/album22.jpg
    - assets/album23.jpg
    - assets/album24.jpg
    - assets/album25.jpg
    - assets/album26.jpg
    - assets/album27.jpg
    - assets/album28.jpg
    - assets/album29.jpg
    - assets/album30.jpg
    - assets/album31.jpg
    - assets/album32.jpg
    - assets/album33.jpg
    - assets/album34.jpg
    - assets/album35.jpg
    - assets/album36.jpg
    - assets/album37.jpg
    - assets/album38.jpg
    - assets/album39.jpg
    - assets/album40.jpg
    - assets/album41.jpg
    - assets/album42.jpg
    - assets/album43.jpg
    - assets/album44.jpg
    - assets/album45.jpg
    - assets/album46.jpg
    - assets/album47.jpg
    - assets/album48.jpg
    - assets/album49.jpg
    - assets/album50.jpg
    - assets/album51.png
    - assets/invitacion.png
    - assets/default.png
    - assets/vanilla.png
    - assets/church.png
    - assets/party.png
    - assets/liverpool.jpg
    - assets/sears.png
    - assets/alcancias.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
